### ISSUE TITLE
After today's update (v1.1.1) it stopped working, error in js console

### ISSUE THREAD

**Issue by admg** [Mimeo/VSTSExtension-ActivePullRequests#53]
Not showing pull requests, there's an error in js console in browser. TFS is on premise.

![image](https://user-images.githubusercontent.com/9196367/60874153-dd3a5780-a237-11e9-990f-0ee4a89053e2.png)

`bundle.js:53 Uncaught (in promise) TFS.WebApi.Exception: 404: Not Found
    at Object.<anonymous> (http://***:8080/tfs/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.1/assetbyname/dist/bundle.js:53:51961)
    at http://***:8080/tfs/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.1/assetbyname/dist/bundle.js:53:50486
    at Object.next (http://***:8080/tfs/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.1/assetbyname/dist/bundle.js:53:50591)
    at a (http://***:8080/tfs/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.1/assetbyname/dist/bundle.js:53:49337)`

**Comment by johngraumann** [comment]
We are seeing the same exception. We are running Azure DevOps Server 2019.

**Comment by joelbourbon** [comment]
This is the part in code that probably breaks on premise:
![image](https://user-images.githubusercontent.com/1767435/60971057-5649b580-a2f1-11e9-9c77-f9d6a204bcb0.png)

It also would not work for teams still using the old URLs (organization.visualstudio.com).

Not sure with what it can be replaced....

**Comment by joelbourbon** [comment]
Here is a great article on how URLs should be managed in extensions:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/work-with-urls?view=azure-devops&tabs=nodejsgeneric

**Comment by joelbourbon** [comment]
Oh sorry guys I was wrong. What I found is probably causing other issues.

The bug you found seems to be related to the `BuildRestClient`. The way it is used is fairly straightforward and I don't see how this could be fixed for On-Premise. Seems like an issue in the underlying library used here --> [azure-devops-extension-api](https://www.npmjs.com/package/azure-devops-extension-api)

**Comment by persalmi** [comment]
Is anyone working on a resolution for this problem? The hard reference to dev.azure.com seems easy to fix but is it the whole truth for getting the extension to work on-premise again?

**Comment by wadechandler** [comment]
I'm seeing a definite issue with the cross domain problem mentioned above by @joelbourbon and we have a different URL we access from yet still the SaaS version (as we've been on ADO a long time). It seems the URL the user is already using in the browser should be used versus the hard coded version as mentioned above.

**Comment by nshenoy** [comment]
Closing as stale.
