### ISSUE TITLE
401 Unauthorized error when using on-premise

### ISSUE THREAD

**Issue by sumo300** [Mimeo/VSTSExtension-ActivePullRequests#6]
When this tries to access the TFS Git API, it gets a 401 unauthorized error.  I think there is an issue with the defined scopes for this extension.

https://freerangeeggs.net/2016/02/11/tfs-webapi-exception-401-in-visual-studio-team-services-extension/

**Comment by sumo300** [comment]
Note that you may now need to define scopes for your extension to access parts of the API.

https://freerangeeggs.net/2016/02/11/tfs-webapi-exception-401-in-visual-studio-team-services-extension/

**Comment by nshenoy** [comment]
Thanks for the tip @sumo300! I'll try to update as soon as I can. Unless you wanted to submit a PR?

**Comment by nshenoy** [comment]
@sumo300 @nilleb I just updated the extension to v0.2.5. I don't have a TFS onprem box to test this on. Any chance you could install this and see if it works now?

**Comment by sumo300** [comment]
I just tested 0.2.6 and still get the following error:

```
GET https://tfs-test/tfs/TeamProject/Applications/_apis/git/Repositories?includeLinks=true 401 (Unauthorized)
corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:22 TFS.WebApi.Exception: 401: error
    at k (https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:375)
    at https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:2955
    at d (https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:635)
    at https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:2888
    at l (https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:8122)
    at https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:8348
    at t.when (https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:3780)
    at t.u.promiseDispatch (https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:2824)
    at https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:1649
    at MessagePort.t (https://tfs-test/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:5773)(anonymous function) @ corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:22t @ corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:22
```

**Comment by iamthegD** [comment]
Hi,

we have the same issue. cool plugin though

**Comment by nshenoy** [comment]
@iamthegD @sumo300 I know it's been a while, but if you're still using TFS on-premises, could you give the latest a shot? Please uninstall the old extension and install the new one from here: https://marketplace.visualstudio.com/items?itemName=mimeo-vs-marketplace.mimeo-active-pull-requests . Note that this is under a different publisher name, thus you'll need to uninstall the old one. Update the thread and let me know if it works for you now. Thanks!

**Comment by nshenoy** [comment]
Closing due to inactivity. If this is still an issue with on-premises TFS, feel free to reopen.
