### ISSUE TITLE
Not loading on Azure Devops server

### ISSUE THREAD

**Issue by modestotech** [Mimeo/VSTSExtension-ActivePullRequests#72]
I've just installed the extension on a server installation and installation went fine.
I followed the instructions [here](https://marketplace.visualstudio.com/acquisition?itemName=mimeo-vs-marketplace.mimeo-active-pull-requests):
- To install "All Active Pull Requests" on Azure DevOps Server, perform following steps:
- Navigate to the Azure DevOps Server Extensions page on your server. (For example, http://someserver/_gallery/manage)
- Click upload new extension and select the file you have just downloaded.
- After the extension has successfully uploaded, click Install and select the Team Project Collection to install into.

But no no data is loaded in the UI, I only get this placeholder image:
![image](https://user-images.githubusercontent.com/31730051/69429987-1251cd00-0d35-11ea-8d2d-dc301700e232.png)

This error from the console might be related
```text
bundle.js:53 Uncaught (in promise) TFS.WebApi.Exception: 404: Not Found
    at Object.<anonymous> (https://devops.inyett.se/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.5/assetbyname/dist/bundle.js:53:53852)
    at https://devops.inyett.se/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.5/assetbyname/dist/bundle.js:53:52377
    at Object.next (https://devops.inyett.se/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.5/assetbyname/dist/bundle.js:53:52482)
    at a (https://devops.inyett.se/_apis/public/gallery/publisher/mimeo-vs-marketplace/extension/mimeo-active-pull-requests/1.1.5/assetbyname/dist/bundle.js:53:51228)
```

Tell me what's necessary to troubleshoot, or if anything more is necessary from my end.

**Comment by modestotech** [comment]
After updating the Azure Devops server to the latest version, the extension works.
